android.nonFinalResIds=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx6144m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.warning.mode=all

### Gru Android configuration ###
projectMinSdk=26
projectTargetSdk=36
projectCompileSdk=36

projectVersionCode=128
projectVersionName=0.2.0
